### ISSUE TITLE
Finish the "Habit" use cases

### ISSUE THREAD

**Issue by DLukeNelson** [CMPUT301F17T26/Smores#3]

**Comment by farhadmak** [comment]
06d22555d00fea1607edbc9b290d8c739ebaccdb

**Comment by farhadmak** [comment]
486d35bd2ad24d7950427c1a7a2bdf8fe4310cda
e960bcefb13f81b2a151f2f478ffddf1f4ce804c

**Comment by farhadmak** [comment]
a9fd0fa198c896d39afe87752f78f84e58f97850

**Comment by farhadmak** [comment]
dcd21ef4600b938fd9ed4707a966f34365546013

**Comment by farhadmak** [comment]
da82398fa3656bc50aa75a459f6b2541fdab6e07

**Comment by farhadmak** [comment]
368e6769b47f063768d5474c3b6b981a5bf95f43
