### ISSUE TITLE
Habit Detail Start date constraint

### ISSUE THREAD

**Issue by AkashPatelUAlberta** [CMPUT301F17T26/Smores#44]
Need to place constraint on the start date the user is allowed to change.

**Comment by AkashPatelUAlberta** [comment]
Clicking the back arrow in the top left corner of a detail page navigates to the today tab instead of the previous activity.

**Comment by AkashPatelUAlberta** [comment]
Need to prevent user for setting start date prior to today.

**Comment by DLukeNelson** [comment]
Also need to prevent them from setting it after the earliest habit event. (when editing)
