### ISSUE TITLE
Stats doesnt update for friend until the other user manually saves the habit

### ISSUE THREAD

**Issue by Brohammers** [CMPUT301F17T26/Smores#72]
Two possible methods of fixing
- Call calculate stats as soon as you retrieve friends states (best way)
- Call calculate states for the user and upload those changes immediately (2nd option, easier but the user still has to open the app for this to happen)

**Comment by DLukeNelson** [comment]
Made an overload for calculate stats so you can give it an arraylist directly. Now friends can calculate stats.

**Comment by Brohammers** [comment]
Reviewed with a few habit events, and stats calculate correctly. SHA: 354749270ce484d6578897d254be84f1f0d190fa
